### PR TITLE
Preserve sub directory structure of less files 

### PR DESCRIPTION
**Pull request by thhalm-talkwalker**
Preserve sub directory structure of less files (relative to defined src folders in the less LanguageSourceSet

### CODE REVIEW

**Comment by jvff** [comment]
Thanks!

**Comment by thhalm-talkwalker** [comment]
Hello jvff,

Is it possible to release a new version 0.0.2 containing this change? 

Thanks in advance!

**Comment by jvff** [comment]
Sure :)

Version 0.0.2 released with the fix.

Thank you!

**Comment by thhalm-talkwalker** [comment]
:thumbsup: Great news :-)

**Pull request merged**
